### ISSUE TITLE
Error translating simple logic conditions with dynamics

### ISSUE THREAD

**Issue by igor-kostromin** [sq/JSIL#374]
Error when translating next code (tried in http://jsil.org/try/):

```
using System;

public class Program {
    public static void Main () {
        dynamic i = 5;
        if (i < 10 && true)
          Console.WriteLine("Ok");
    }
}
```

StackTrace:

> ...
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotImplementedException: The unary operator 'IsFalse' is not implemented.
> ...
> Unhandled exception: Error: The function 'System.Void Program::Main()' could not be translated.
> Error: The function 'System.Void Program::Main()' could not be translated.
> at UntranslatableFunctionInvoked (http://jsil.org/try/Libraries/JSIL.Core.js:1177:21)
> at runScript (http://jsil.org/try/output_frame.js:80:5)
> at runTranslatedJS (http://jsil.org/try/index.js?v6:597:20)

**Comment by callanh** [comment]
I've just hit 'The unary operator 'IsFalse' is not implemented'.  Is this the same issue as above?

**Comment by kg** [comment]
Yeah, same problem.

**Comment by callanh** [comment]
I guess it is a low priority given the last timestamp?  I'd like to contribute but I suspect my learning curve is not at this level yet.

**Comment by kg** [comment]
Dynamic isn't used much and in particular using it this way isn't especially necessary. It'll get fixed eventually.

**Comment by callanh** [comment]
Ah I've misunderstood the issue so thanks for clarifying - I thought it was unary operators in general and not specific to dynamics.  I've only come across it because I'm using the javascript dynamic objects.  The workaround is no problem at all.

**Comment by iskiselev** [comment]
I suppose it was found on VS 2015? Roslyn changed a lot of code-generation patterns and lot's of dynamic is broken if source assembly compiled with it.
I personally believe, that proper way to work with dynamic - don't try to change their semantics (as it may be broken once again with next Roslyn update) and just translate (#531).
But we need support C# Binders for it, and taught binders work with raw JS objects.

**Comment by kg** [comment]
Yeah. Implementing binders is the Right Thing and it will cover more cases. The old dynamic support was a hack that has outlived its usefulness :-)
