### ISSUE TITLE
Out of memory on large conversion

### ISSUE THREAD

**Issue by dbh1997** [sq/JSIL#715]
Looks like I've crossed a threshold that run JSIL out of memory.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Error occurred while
 generating javascript for assembly 'SketchJS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. ---> System.Excep
tion: An error occurred while declaring the type 'Sketch.Busi.RoofLine' ---> System.Exception: An error occurred while d
eclaring the type 'Sketch.Busi.RoofLine/RoofLineType' ---> System.OutOfMemoryException: Exception of type 'System.OutOfM
emoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at JSIL.Internal.JavascriptFormatter.WriteIndentIfNeeded() in c:\sd\JSIL\JSIL\JavascriptFormatter.cs:line 244
   at JSIL.Internal.JavascriptFormatter.WriteRaw(String characters) in c:\sd\JSIL\JSIL\JavascriptFormatter.cs:line 248
   at JSIL.Internal.JavascriptFormatter.Identifier(String name, EscapingMode escapingMode) in c:\sd\JSIL\JSIL\Javascript
Formatter.cs:line 784
   at JSIL.AssemblyTranslator.TranslateEnum(DecompilerContext context, JavascriptFormatter output, TypeDefinition enm, J
avascriptAstEmitter astEmitter) in c:\sd\JSIL\JSIL\AssemblyTranslator.cs:line 1078
   at JSIL.AssemblyTranslator.DeclareType(DecompilerContext context, TypeDefinition typedef, JavascriptAstEmitter astEmi
tter, JavascriptFormatter output, HashSet`1 declaredTypes, Boolean stubbed) in c:\sd\JSIL\JSIL\AssemblyTranslator.cs:lin
e 1270
   --- End of inner exception stack trace ---

I've not looked too deep just yet, but it appears that it writes to a memory stream, then dumps that into a byte array which is held in a dictionary.  At some point the resizing operation on the stream can long longer find a contiguous block when increasing the size.

                if (!Manifest.GetExistingSize(assembly, out existingSize)) {
                    using (var outputStream = new MemoryStream(DefaultStreamCapacity)) {

                        var context = MakeDecompilerContext(assembly.MainModule);

                        try {
                            Translate(context, assembly, outputStream);   // 
                        } catch (Exception exc) {
                            throw new Exception("Error occurred while generating javascript for assembly '" + assembly.FullName + "'.", exc);
                        }

                        var segment = new ArraySegment<byte>(
                            outputStream.GetBuffer(), 0, (int)outputStream.Length
                        );

                        result.AddFile("Script", outputPath, segment);

                        Manifest.SetAlreadyTranslated(assembly, outputStream.Length);
                    }

                    lock (result.Assemblies)
                        result.Assemblies.Add(assembly);
                } else {
                    Console.WriteLine(String.Format("Skipping '{0}' because it is already translated...", assembly.Name));

// Eventually Translate gets into this function and the Output.Write throws a memory exception.  The dump of the strings going in doesn't show anything unusually large going in just before it goes down, there are just a lot of lines. 

        public void WriteRaw (string characters) {
            WriteIndentIfNeeded();
            Console.WriteLine(characters);    // Added to see if something looked suspicious
            Output.Write(characters);
        }

I can probably rework the Memory Stream to a File Stream and have the dictionary store temp file names, but wanted to see if there were other alternatives (maybe compile with 64 bit) that anybody has used.  By the time it gets into the above code, the private bytes for JSIL.exe are already at 1.1 gig, so there may be another looming memory issue even if this spot is corrected.

**Comment by kg** [comment]
Odd that this would happen at 1.1gb. I don't think those streams are much of the actual memory usage...

One option here is to do translation sequentially, one assembly at a time, then discard all the data for the assembly once it's translated. JSIL doesn't do that right now but there aren't any terribly good reasons for it. Minor threading gains at most.

How easy would this be for me to reproduce?

On March 12, 2015 7:39:45 AM PDT, dbh1997 <notifications@github.com> wrote:
>Looks like I've crossed a threshold that run JSIL out of memory.
>
>Unhandled Exception: System.AggregateException: One or more errors
>occurred. ---> System.Exception: Error occurred while
>generating javascript for assembly 'SketchJS, Version=0.0.0.0,
>Culture=neutral, PublicKeyToken=null'. ---> System.Excep
>tion: An error occurred while declaring the type 'Sketch.Busi.RoofLine'
>---> System.Exception: An error occurred while d
>eclaring the type 'Sketch.Busi.RoofLine/RoofLineType' --->
>System.OutOfMemoryException: Exception of type 'System.OutOfM
>emoryException' was thrown.
>   at System.IO.MemoryStream.set_Capacity(Int32 value)
>   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
>at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32
>count)
>at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean
>flushEncoder)
>   at System.IO.StreamWriter.Write(String value)
>at JSIL.Internal.JavascriptFormatter.WriteIndentIfNeeded() in
>c:\sd\JSIL\JSIL\JavascriptFormatter.cs:line 244
>at JSIL.Internal.JavascriptFormatter.WriteRaw(String characters) in
>c:\sd\JSIL\JSIL\JavascriptFormatter.cs:line 248
>at JSIL.Internal.JavascriptFormatter.Identifier(String name,
>EscapingMode escapingMode) in c:\sd\JSIL\JSIL\Javascript
>Formatter.cs:line 784
>at JSIL.AssemblyTranslator.TranslateEnum(DecompilerContext context,
>JavascriptFormatter output, TypeDefinition enm, J
>avascriptAstEmitter astEmitter) in
>c:\sd\JSIL\JSIL\AssemblyTranslator.cs:line 1078
>at JSIL.AssemblyTranslator.DeclareType(DecompilerContext context,
>TypeDefinition typedef, JavascriptAstEmitter astEmi
>tter, JavascriptFormatter output, HashSet`1 declaredTypes, Boolean
>stubbed) in c:\sd\JSIL\JSIL\AssemblyTranslator.cs:lin
>e 1270
>   --- End of inner exception stack trace ---
>
>
>I've not looked too deep just yet, but it appears that it writes to a
>memory stream, then dumps that into a byte array which is held in a
>dictionary.  At some point the resizing operation on the stream can
>long longer find a contiguous block when increasing the size.
>
>           if (!Manifest.GetExistingSize(assembly, out existingSize)) {
>   using (var outputStream = new MemoryStream(DefaultStreamCapacity)) {
>
>              var context = MakeDecompilerContext(assembly.MainModule);
>
>                        try {
>                      Translate(context, assembly, outputStream);   // 
>                        } catch (Exception exc) {
>throw new Exception("Error occurred while generating javascript for
>assembly '" + assembly.FullName + "'.", exc);
>                        }
>
>                        var segment = new ArraySegment<byte>(
>                  outputStream.GetBuffer(), 0, (int)outputStream.Length
>                        );
>
>                        result.AddFile("Script", outputPath, segment);
>
>          Manifest.SetAlreadyTranslated(assembly, outputStream.Length);
>                    }
>
>                    lock (result.Assemblies)
>                        result.Assemblies.Add(assembly);
>                } else {
>Console.WriteLine(String.Format("Skipping '{0}' because it is already
>translated...", assembly.Name));
>
>// Eventually Translate gets into this function and the Output.Write
>throws a memory exception.  The dump of the strings going in doesn't
>show anything unusually large going in just before it goes down, there
>are just a lot of lines. 
>
>        public void WriteRaw (string characters) {
>            WriteIndentIfNeeded();
>Console.WriteLine(characters);    // Added to see if something looked
>suspicious
>            Output.Write(characters);
>        }
>
>
>I can probably rework the Memory Stream to a File Stream and have the
>dictionary store temp file names, but wanted to see if there were other
>alternatives (maybe compile with 64 bit) that anybody has used.  By the
>time it gets into the above code, the private bytes for JSIL.exe are
>already at 1.1 gig, so there may be another looming memory issue even
>if this spot is corrected.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sq/JSIL/issues/715

- kg (mobile)

**Comment by dbh1997** [comment]
It doesn’t really appear to be, it’s probably just the spot that put it over.  So reworking it to another type of stream would probably only buy me a little more time before something else was the end cause.

By the time it crashes, it shows 1.143 gigs – which isn’t much more.  In past experiences, it seems like 1.2 – 1.4g is the range at which 32 bit C# programs start having troubles, and fragmented memory prohibits the memory manager from being able to get large contiguous blocks of memory.

I can’t really send the entire package of source for you to try – at least not without some fairly serious hoops on my side.  I’ve pressed all the code I need into one assembly for convenience that currently that results in a .JS file of 26.3. megs (before the last extra pieces I added in).  I can break this down into assemblies and that might also give it some wiggle room to find contiguous memory.  Perhaps that’s a better place to start.

**Comment by dbh1997** [comment]
For whatever it’s worth, changing it to 64 bit does work.  The memory usage peaks at about 6 gigs now (I was only expecting it to double).

**Comment by matra774** [comment]
Default memoryStream doubles its internal buffer each time all allocated memory has been used, which is not the best allocation strategy for large streams :-) MS recently released RecycableMemoryStream which solves this (and some other problems). Tak a look at http://www.philosophicalgeek.com/2015/02/06/announcing-microsoft-io-recycablememorystream/

**Comment by Lambdac0re** [comment]
+1

**Comment by iskiselev** [comment]
Have you tried to use 64bot version (jsilc.anycpu)? The only problem with it, that it will not be able to translate XNA resources.
