### ISSUE TITLE
Variables that contain only underscores and numbers can crash

### ISSUE THREAD

**Issue by dbh1997** [sq/JSIL#743]
This started happening after bringing the repository up to date - 6/21/15 (so sometime in the past couple months).  

This sounds like a stupid thing to do and generally speaking it would be, but we had a matrix class that has each cell unrolled for performance.  The coder just used underscore followed by row and column to keep the names compact.

    public class Mat4 : IDumpableObject
    {
        #region Data Members
        private double _00, _01, _02, _03;
        private double _10, _11, _12, _13;
        private double _20, _21, _22, _23;
        private double _30, _31, _32, _33;

        #endregion

   ...
   }

Easy fix was to rename each as _cellXY and the problem goes away...  I've not managed to reproduce it by using this type of variable name as a local member of a function or in a simple class, so it takes more than just the name to get the problem to trigger - perhaps quite a bit more.  I will look more when I get some time, and clearly not a high priority - but hey, there it is on the off chance somebody else bumps into the crash...

This is the call stack,  It repeats for all 12

1>  // Decompiling  ............................// Error occurred while translating node stloc:float64(, ldfld:float64(Mat4::_33, ldloc:Mat4(this))): System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
1>     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
1>     at JSIL.Ast.JSIndirectVariable..ctor(IDictionary`2 variables, String identifier, MethodReference function) in c:\sd\JSIL\JSIL\AST\JSIdentifierTypes.cs:line 712
1>     at JSIL.ILBlockTranslator.MakeIndirectVariable(String name) in c:\sd\JSIL\JSIL\ILBlockTranslator.cs:line 519
1>     at JSIL.ILBlockTranslator.MapVariable(ILVariable variable) in c:\sd\JSIL\JSIL\ILBlockTranslator.cs:line 2105
1>     at JSIL.ILBlockTranslator.Translate_Stloc(ILExpression node, ILVariable variable) in c:\sd\JSIL\JSIL\ILBlockTranslator.cs:line 2137

**Comment by kg** [comment]
Was it an intermittent failure or did the application fail to compile consistently every time?

**Comment by dbh1997** [comment]
It's consistent best I can tell.

**Comment by kg** [comment]
OK. Does it decompile correctly in ILSpy, do you know?

**Comment by dbh1997** [comment]
It compiles fine except for the function that contains the issue is missing from the output.  I'm chisling down the large class right now to get the minimal set.  Hopefully I can provide you that in the next 15 minutes give or take.

**Comment by dbh1997** [comment]
Ok.  The issues appears when you include a  multi-dim array setter.  Construct one of these classes and do an assignment m[0,0] = 0.0 for example.  I'm guessing the switch statement can be removed as well to make the example even tighter.

    public class Matrix4
    {
        private double _00;     // other 15 vars removed for brevity

        public Matrix4()
        {
            _00 = 1.0;
        }

    	public double this[int row, int col]
    	{
    	    set
    	    {
                // Other 15 cases removed for brevity
                switch (row)
                {
                    case 0:
                        switch (col)
                        {
                            case 0:
                                _00 = value;
                                break;
                        }
                        break;
                }
            }
    	}
}

**Comment by dbh1997** [comment]
Yep, the following is enough...

    	public double this[int row, int col]
    	{
    	    set
    	    {
                _00 = value;
            }
    	}

**Comment by kg** [comment]
Not reproducible here. Did I overlook something in my test?

**Comment by dbh1997** [comment]
I can still get this one to happen.  I renamed one of the members vars back to _00 and the problem comes back.  There must be a little more to this issue.  I will attempt to pare the class way back tomorrow and try to come up with a better minimum case.  Pretty obscure whatever it is, but I do remember it being a new issue when I updated (whenever the entry was first added).


[cid:image001.png@01D0E409.3ADA5490]

**Comment by kg** [comment]
If it's easier, just send me a .dll or .exe that exhibits the problem so I can check it out in ILSpy and see what happens when I translate it.

**Comment by dbh1997** [comment]
Hmmm…  ILSpy must have a glitch, or the compiler itself (although you would think it wouldn’t work in .NET either…).  I’ll work on an exe next…

// Sketch.Sys.Mat4
public void RotateXY(double cosTheta, double sinTheta)
{
    double num = -sinTheta;
    double  = this._00;
    double cell = this._cell01;
    double cell2 = this._cell02;
    double cell3 = this._cell03;
    this._00 = cosTheta *  + num * this._cell10;
    this._cell10 = sinTheta *  + cosTheta * this._cell10;
    this._cell01 = cosTheta * cell + num * this._cell11;
    this._cell11 = sinTheta * cell + cosTheta * this._cell11;
    this._cell02 = cosTheta * cell2 + num * this._cell12;
    this._cell12 = sinTheta * cell2 + cosTheta * this._cell12;
    this._cell03 = cosTheta * cell3 + num * this._cell13;
    this._cell13 = sinTheta * cell3 + cosTheta * this._cell13;
}

**Comment by dbh1997** [comment]
My attempt to pull it out into a small exe results in it not having any trouble.  ILSpy looks fine as well.  It even uses “txx” instead of “cellxx” for the temporary var names which is pretty curious – you would think on a function by function basis would always use the same pattern.  Attached is my attempt just in case it ever needs to be revived again.

Adding the interface didn’t make a difference either.  I could attempt to expand it to include all the uncalled members and pull in more classes, but at this point it’s not worth it, so I’d keep it closed and chalk it up to something obscure.

Thanks,
Dave.

**Comment by kg** [comment]
Could debug information be the problem? ILSpy (thus JSIL) uses debug information to pick variable names. Make sure you have the .pdb/.mdb file in the right place.
