### ISSUE TITLE
Generating code for proxied struct fails

### ISSUE THREAD

**Issue by wizzard0** [sq/JSIL#841]
Fixing flags for JSProxyAttribute so it can be set on structs (#839) didnt help:

```
// Writing JS   ........................System.AggregateException: One or more errors occurred. ---> System.Exception: Error occurred while generating javascript for assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5
c561934e089'. ---> System.Exception: An error occurred while declaring the type 'System.ArraySegment`1' ---> System.Collections.Generic.KeyNotFoundException: No cache entry for method '[mscorlib]System.ArraySegment`1 System.Boolean Equals (
 System.Object )'.
   at JSIL.FunctionCache.GetCacheEntry(QualifiedMemberIdentifier method, Boolean throwOnFail) in c:\dev\jsil_experiments\JSIL_master\JSIL\FunctionCache.cs:line 145
   at JSIL.FunctionCache.GetExpression(QualifiedMemberIdentifier method) in c:\dev\jsil_experiments\JSIL_master\JSIL\FunctionCache.cs:line 152
   at JSIL.AssemblyTranslator.GetFunctionBodyForMethod(Boolean isExternal, MethodInfo methodInfo) in c:\dev\jsil_experiments\JSIL_master\JSIL\AssemblyTranslator.cs:line 1992
   at JSIL.AssemblyTranslator.EmitTypeMethodExpressions(DecompilerContext context, TypeDefinition typedef, IAstEmitter astEmitter, IAssemblyEmitter assemblyEmitter, Boolean stubbed, JSRawOutputIdentifier dollar, Int32& nextDisambiguatedId)
in c:\dev\jsil_experiments\JSIL_master\JSIL\AssemblyTranslator.cs:line 1174
   at JSIL.AssemblyTranslator.DeclareType(DecompilerContext context, TypeDefinition typedef, IAstEmitter astEmitter, IAssemblyEmitter assemblyEmitter, HashSet`1 declaredTypes, Boolean stubbed) in c:\dev\jsil_experiments\JSIL_master\JSIL\Ass
emblyTranslator.cs:line 1075
   --- End of inner exception stack trace ---
   at JSIL.AssemblyTranslator.DeclareType(DecompilerContext context, TypeDefinition typedef, IAstEmitter astEmitter, IAssemblyEmitter assemblyEmitter, HashSet`1 declaredTypes, Boolean stubbed) in c:\dev\jsil_experiments\JSIL_master\JSIL\Ass
emblyTranslator.cs:line 1101
   at JSIL.AssemblyTranslator.TranslateModule(DecompilerContext context, IAssemblyEmitter assemblyEmitter, ModuleDefinition module, HashSet`1 sealedTypes, HashSet`1 declaredTypes, Boolean stubbed) in c:\dev\jsil_experiments\JSIL_master\JSIL
\AssemblyTranslator.cs:line 978
   at JSIL.AssemblyTranslator.TranslateSingleAssemblyInternal(DecompilerContext context, AssemblyDefinition assembly, Stream outputStream) in c:\dev\jsil_experiments\JSIL_master\JSIL\AssemblyTranslator.cs:line 933
   at JSIL.AssemblyTranslator.<>c__DisplayClass18.<TranslateInternal>b__17(Int32 i) in c:\dev\jsil_experiments\JSIL_master\JSIL\AssemblyTranslator.cs:line 542
   --- End of inner exception stack trace ---
   at JSIL.AssemblyTranslator.<>c__DisplayClass18.<TranslateInternal>b__17(Int32 i) in c:\dev\jsil_experiments\JSIL_master\JSIL\AssemblyTranslator.cs:line 564
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object param0)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at JSIL.AssemblyTranslator.TranslateInternal(String assemblyPath, Boolean scanForProxies) in c:\dev\jsil_experiments\JSIL_master\JSIL\AssemblyTranslator.cs:line 568
   at JSIL.AssemblyTranslator.Translate(String assemblyPath, Boolean scanForProxies) in c:\dev\jsil_experiments\JSIL_master\JSIL\AssemblyTranslator.cs:line 458
   at JSIL.Compiler.Profiles.Default.Translate(VariableSet variables, AssemblyTranslator translator, Configuration configuration, String assemblyPath, Boolean scanForProxies) in c:\dev\jsil_experiments\JSIL_master\Compiler\Profiles\Default.
cs:line 23
   at JSIL.Compiler.Program.InternalMain(String[] arguments) in c:\dev\jsil_experiments\JSIL_master\Compiler\Program.cs:line 800
   at JSIL.Compiler.Program.Main(String[] arguments) in c:\dev\jsil_experiments\JSIL_master\Compiler\Program.cs:line 692
---> (Inner Exception #0) System.Exception: Error occurred while generating javascript for assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. ---> System.Exception: An error occurred while declaring the
type 'System.ArraySegment`1' ---> System.Collections.Generic.KeyNotFoundException: No cache entry for method '[mscorlib]System.ArraySegment`1 System.Boolean Equals ( System.Object )'.
   at JSIL.FunctionCache.GetCacheEntry(QualifiedMemberIdentifier method, Boolean throwOnFail) in c:\dev\jsil_experiments\JSIL_master\JSIL\FunctionCache.cs:line 145
   at JSIL.FunctionCache.GetExpression(QualifiedMemberIdentifier method) in c:\dev\jsil_experiments\JSIL_master\JSIL\FunctionCache.cs:line 152
   at JSIL.AssemblyTranslator.GetFunctionBodyForMethod(Boolean isExternal, MethodInfo methodInfo) in c:\dev\jsil_experiments\JSIL_master\JSIL\AssemblyTranslator.cs:line 1992
   at JSIL.AssemblyTranslator.EmitTypeMethodExpressions(DecompilerContext context, TypeDefinition typedef, IAstEmitter astEmitter, IAssemblyEmitter assemblyEmitter, Boolean stubbed, JSRawOutputIdentifier dollar, Int32& nextDisambiguatedId)
in c:\dev\jsil_experiments\JSIL_master\JSIL\AssemblyTranslator.cs:line 1174
   at JSIL.AssemblyTranslator.DeclareType(DecompilerContext context, TypeDefinition typedef, IAstEmitter astEmitter, IAssemblyEmitter assemblyEmitter, HashSet`1 declaredTypes, Boolean stubbed) in c:\dev\jsil_experiments\JSIL_master\JSIL\Ass
emblyTranslator.cs:line 1075
   --- End of inner exception stack trace ---
   at JSIL.AssemblyTranslator.DeclareType(DecompilerContext context, TypeDefinition typedef, IAstEmitter astEmitter, IAssemblyEmitter assemblyEmitter, HashSet`1 declaredTypes, Boolean stubbed) in c:\dev\jsil_experiments\JSIL_master\JSIL\Ass
emblyTranslator.cs:line 1101
   at JSIL.AssemblyTranslator.TranslateModule(DecompilerContext context, IAssemblyEmitter assemblyEmitter, ModuleDefinition module, HashSet`1 sealedTypes, HashSet`1 declaredTypes, Boolean stubbed) in c:\dev\jsil_experiments\JSIL_master\JSIL
\AssemblyTranslator.cs:line 978
   at JSIL.AssemblyTranslator.TranslateSingleAssemblyInternal(DecompilerContext context, AssemblyDefinition assembly, Stream outputStream) in c:\dev\jsil_experiments\JSIL_master\JSIL\AssemblyTranslator.cs:line 933
   at JSIL.AssemblyTranslator.<>c__DisplayClass18.<TranslateInternal>b__17(Int32 i) in c:\dev\jsil_experiments\JSIL_master\JSIL\AssemblyTranslator.cs:line 542
   --- End of inner exception stack trace ---
   at JSIL.AssemblyTranslator.<>c__DisplayClass18.<TranslateInternal>b__17(Int32 i) in c:\dev\jsil_experiments\JSIL_master\JSIL\AssemblyTranslator.cs:line 564
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object param0)<---

```

**Comment by wizzard0** [comment]
Still reproducible as of https://github.com/sq/JSIL/commit/b4f2ff8867a05158727bbd58e7c56b3fe0b009e7
