### ISSUE TITLE
does JSIL lack console input support?

### ISSUE THREAD

**Issue by 0xFireball** [sq/JSIL#940]
running the code:

using System;

public static class Program {
    public static unsafe void Main (string[] args) {
        Console.WriteLine("Hello, World!");
        string name = Console.ReadLine();
      	Console.WriteLine(name);
    }
}

produces:

Hello, World!
Unhandled exception: TypeError: $T01(...).ReadLine is not a function
TypeError: $T01(...).ReadLine is not a function
at Program_Main (eval at <anonymous> (http://jsil.org/try/output_frame.js:70:41), <anonymous>:29:23)
at window.runScript (http://jsil.org/try/output_frame.js:80:5)
at runTranslatedJS (http://jsil.org/try/index.js?v6:602:20)

on the try webpage.

Does JSIL lack Console.ReadLine/etc. support?

**Comment by kg** [comment]
There's no built-in stdin since the browser has no equivalent.
