### ISSUE TITLE
MemberwiseClone of Color

### ISSUE THREAD

**Issue by 0xFireball** [sq/JSIL#943]
the C# code 
    Color backColor = Color.Black;

results in JSIL:
    this.backColor = $T03().get_Black().MemberwiseClone();

which in turn results in the error:
Uncaught TypeError: Cannot read property 'MemberwiseClone' of undefined

**Comment by 0xFireball** [comment]
Stack trace:
The external method 'void .ctor()' of type 'Microsoft.Xna.Framework.GameComponentCollection' has not been implemented; calling inherited method.
    at Object.JSIL.Host.warning (http://localhost/devbox/jsil/thhd/JSIL/lib/JSIL.Host.js:153:15)
    at Object.JSIL.WarningFormat (http://localhost/devbox/jsil/thhd/JSIL/lib/JSIL.Core.js:10666:13)
    at Object.ExternalMemberStub (http://localhost/devbox/jsil/thhd/JSIL/lib/JSIL.Core.js:1313:14)
    at Object.$internalCtor (http://localhost/devbox/jsil/thhd/JSIL/lib/XNA/XNA4.js:1118:10)
    at Object.Microsoft_Xna_Framework_GameComponentCollection_CreateInstanceOfType (jsil://closure/Microsoft.Xna.Framework.GameComponentCollection.CreateInstanceOfType:8:30)
    at Object.JSIL.CreateInstanceOfType$CacheHit (http://localhost/devbox/jsil/thhd/JSIL/lib/JSIL.Core.js:8952:14)
    at Object.JSIL.CreateInstanceOfType$CacheMiss (http://localhost/devbox/jsil/thhd/JSIL/lib/JSIL.Core.js:8928:15)
    at Object.JSIL.CreateInstanceOfType (http://localhost/devbox/jsil/thhd/JSIL/lib/JSIL.Core.js:8978:17)
    at Object._ctor (http://localhost/devbox/jsil/thhd/JSIL/lib/XNA/XNA4.js:1170:30
JSIL.Browser.js:200 The external method 'Microsoft.Xna.Framework.Color get_Black()' of type 'Microsoft.Xna.Framework.Color' has not been implemented.
    at Object.JSIL.Host.warning (http://localhost/devbox/jsil/thhd/JSIL/lib/JSIL.Host.js:153:15)
    at Object.JSIL.WarningFormat (http://localhost/devbox/jsil/thhd/JSIL/lib/JSIL.Core.js:10666:13)
    at Function.ExternalMemberStub (http://localhost/devbox/jsil/thhd/JSIL/lib/JSIL.Core.js:1336:14)
    at Function.PreInitMethod_Invoke (http://localhost/devbox/jsil/thhd/JSIL/lib/JSIL.Core.js:766:21)
    at Object.Thunderhead__ctor (http://localhost/devbox/jsil/thhd/Thunderhead,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null.js:1096:29)
    at Object.Thunderhead_Thunderhead (jsil://closure/Thunderhead.Thunderhead:17:21)
    at runMain (http://localhost/devbox/jsil/thhd/:57:20)
    at browserFinishedLoadingCallback (http://localhost/devbox/jsil/thhd/JSIL/lib/JSIL.Browser.js:1139:9
Thunderhead, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.js:1096 Uncaught TypeError: Cannot read property 'MemberwiseClone' of undefined

**Comment by 0xFireball** [comment]
if color is not implemented, how do I set the background color?

**Comment by kg** [comment]
Make sure you enabled the xna libraries in your ```jsilConfig``` JS object when loading the game.

**Comment by kg** [comment]
To be more precise, like so:
https://github.com/sq/JSIL/blob/master/jsil.org/demos/Platformer/Platformer.html#L16

**Comment by 0xFireball** [comment]
how would i do that?

**Comment by 0xFireball** [comment]
this is my JSILCONFIG

<script type="text/javascript">
      var jsilConfig = {
        printStackTrace: false,
        webgl2d: true,
        xna: 4,
        manifests: [
          "Thunderhead.exe",
          "Content/ThunderheadContent.contentproj"
        ],
        
        showProgressBar: true,
        showStats: true,

        scriptRoot: "",
        libraryRoot: "JSIL/lib/",
        fileRoot: "",
        contentRoot: "Content/"
      };
    </script>

**Comment by iskiselev** [comment]
Probably static properties with colors are not implemented. try to create color through constructor.

**Comment by kg** [comment]
IIRC the color properties are specifically generated during the XNA build process, and I don't think that will happen without a .sln file being built. It produces an XNA.Colors.js or something.
